feat: show user and device location on map
commaai/new-connect pull request #115
Opened 2024-12-13 07:08 UTC by jtgi

fixes: https://github.com/commaai/new-connect/issues/47
based on: https://github.com/commaai/new-connect/pull/54

https://github.com/user-attachments/assets/e514a7fe-fcc3-4d90-9be8-e38cc9ff3670

2025-01-02 13:52 UTC, incognitojam commented
This looks nice! I don't think the `last_gps_lat` and `last__gps_lng` are ever populated in the API though, old connect uses [`GET /v1/devices/:dongle_id/location`](https://api.comma.ai/#device-location) instead

2025-01-03 17:57 UTC, jtgi commented
> This looks nice! I don't think the `last_gps_lat` and `last_gps_lng` are ever populated in that part of the API though, old connect uses [`GET /v1/devices/:dongle_id/location`](https://api.comma.ai/#device-location) instead

Nice catch, ty. Updated to use that endpoint.

Quick note though, the endpoint 403s. I assume its because of the demo account since old connect does as well.
Works fine when I mock though and based on [comma-api  spec[(https://github.com/commaai/comma-api/blob/master/openapi.yaml#L183-L215) I expect it to work.

Got a device you can try it with? Def need to get one setup or mocked.

2025-01-03 19:00 UTC, incognitojam commented
Yes it works for me :slightly_smiling_face:
![image](https://github.com/user-attachments/assets/5f1479a5-f780-437b-a5e0-93fce0c5d3af)

I think not having a location for the demo car is OK for now - there's an argument that should be added on the backend the same way the demo routes are available. Would be nice to have the option to mock different data in the future too.

I noticed the "Show my location" button doesn't work on Firefox. It asks me to allow access to my location, but after that no marker for my location appears on the map. There's no error in the console either. It works fine in Chrome.

2025-01-04 05:27 UTC, jtgi commented
> Yes it works for me 
nice, thanks.

> I noticed the "Show my location" button doesn't work on Firefox. It asks me to allow access to my location, but after that no marker for my location appears on the map. There's no error in the console either. It works fine in Chrome.
Thanks, fixed this and learned a bit about browser implementation differences with geolocation.

Key difference: Safari and Firefox only acknowledge the permission as granted and fires events if you explicitly check 'Remember this for next time'. If the user allows for the current session only, change events don't fire and the permission will still return as 'not granted'. Chrome handles as I expected though.

Fix was to consume the position directly from the `navigation.geolocation.getCurrentPosition` call and not strictly rely on change event.

2025-01-07 01:36 UTC, jtgi commented
@incognitojam lemme know if you have any other feedback, happy to fix up

2025-01-13 12:24 UTC, incognitojam requested changes

2025-01-13 13:14 UTC, incognitojam commented on src/map/index.ts
> +export function getMapStyleId(themeId: string): string {
I don't think this needs to be exported anymore

2025-01-13 13:24 UTC, jtgi commented on src/map/index.ts
> +export function getMapStyleId(themeId: string): string {
yep, removed

2025-01-13 15:15 UTC, incognitojam approved these changes

2025-01-13 15:23 UTC, merged

2025-01-13 15:30 UTC, incognitojam commented
Thanks for the PR! You can open a ticket at `https://comma.ai/support?topic=Shop%20Order` to claim your bounty, just provide a link to this PR

2025-01-13 20:58 UTC, jtgi commented
@incognitojam awesome – thanks for the reviews and touch ups.